config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  namespace :api, defaults: { format: :json } do
    resources :cars do
      resources :features, only: [:index]
    end
  end

  # resources :makes, only: [:index, :show] do
  #   resources :models, only: [:index]
  # end
  # resources :models, only: [:show]

  root to: 'static_pages#root'
end

app/models/car.rb
class Car < ActiveRecord::Base
  validates :make, :model, :trim_name, :trim_number, :price, presence: true

  belongs_to :user
  has_many :features, dependent: :destroy
  accepts_nested_attributes_for :features
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  belongs_to :car
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :session_token, presence: true
  validates :password, length: { minimum: 1, allow_nil: true }
  validates :username, uniqueness: true

  has_many :cars

  attr_reader :password
  after_initialize :ensure_session_token

  def self.find_by_credentials(user_params)
    user = User.find_by_username(user_params[:username])
    user.try(:is_password?, user_params[:password]) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  protected

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
  end
end

app/controllers/api/cars_controller.rb
module Api
  class CarsController < ApiController
    wrap_parameters :car, include: [:make, :model, :trim_name, :trim_number, :price, :features_attributes]

    def create
      @car = current_user.cars.new(car_params)
      if @car.save
        render json: @car
      else
        render json: @car.errors.full_messages, status: :unprocessable_entity
      end
    end

    def update
      @car = current_user.cars.find(params[:id])
      if @car.save
        render json: @car
      else
        render json: @car.errors.full_messages, status: :unprocessable_entity
      end
    end

    def index
      @cars = current_user.cars
      render json: @cars
    end

    def destroy
      @car = current_user.cars.find(params[:id])
      @car.try(:destroy)
      render json: {}
    end

    private

    def car_params
      params.require(:car).permit(
        :make,
        :model,
        :trim_name,
        :trim_number,
        :price,
        {
          :features_attributes => [:name, :description, :price]
        }
      )
    end
  end
end

app/controllers/api/features_controller.rb
module Api
  class FeaturesController < ApplicationController
    def create
      @feature = current_car.features.new(feature_params)

      if @feature.save
        render json: @feature
      else
        render json: @feature.errors.full_messages, status: :unprocessable_entity
      end
    end

    def index
      car = Car.find(params[:car_id])
      render :json => car.features
    end

    private

    def current_car
      if params[:id]
        @feature = Feature.find(params[:id])
        @car = @feature.car
      elsif params[:feature]
        @car = Car.find(params[:feature][:car_id])
      end
    end

    def feature_params
      params.require(:feature).permit(:name, :description, :price)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  private

  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in!(user)
    @current_user = user
    session[:token] = user.reset_token!
  end

  def sign_out!
    current_user.try(:reset_token!)
    session[:token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end

  def require_signed_out!
    redirect_to root_url unless !signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_signed_out!, except: [:destroy]

  def new; end

  def create
    @user = User.find_by_credentials(params[:user])

    if @user
      sign_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Invalid username and/or password"]
      render :new
    end
  end

  def destroy
    sign_out!
    redirect_to new_session_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_signed_in!

  def root; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signed_out!

  def new; end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">AutoWizard</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li>
            <button class="btn btn-primary navbar-btn garage-button">Garage</button>
          </li>
          <li><%= button_to "Sign out", session_url, method: :delete, class: "btn btn-primary navbar-btn" %></li>
        <% else %>
          <li><%= link_to "Log in", new_session_url %></li>
          <li><%= link_to "Sign up", new_user_url %></li>
        <% end %>
      </ul>
  </div>
</div>
</nav>

<% if flash[:errors] %>
<div class="alert alert-danger alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <%= flash[:errors].join("<br>").html_safe %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AutoWizard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="body">
  <%= render partial: "layouts/header" %>
  <!-- <div class="container"> -->
    <%= yield %>
  <!-- </div> -->

</body>
</html>

app/views/static_pages/root.html.erb
<div class="backdrop container">
  <div class="row">
    <div id="pane1" class="col-md-4 off-screen"></div>
    <div id="pane2" class="col-md-4 off-screen"></div>
    <div id="pane3" class="col-md-4 off-screen"></div>
  </div>
  <div id="main"></div>
</div>
<script>$(Final.initialize);</script>

app/views/users/new.html.erb
<div class="sign-up-log-in">

  <header>
    <h1 class="auto-wizard">Sign Up</h1>

    <form action="/users" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <div class="form-group">
        <label>Username<br>
          <input class="user-input" name="user[username]" type="text"><br>
        </label>
      </div>

      <div class="form-group">
        <label>Password<br>
          <input class="user-input" name="user[password]" type="password"><br>
        </label>
      </div>

      <input type="submit" value="Submit" class="btn btn-primary"><br>
    </form>
  </header>

  <div class="wrapper">
    <div class="screen" data-video="/assets/bmw_commercial.mp4">
    </div>
  </div>

  <script>

    var BV,
    isTouch = Modernizr.touch;

    if (!isTouch) {
      // initialize BigVideo
      BV = new $.BigVideo({forceAutoplay:isTouch});
      BV.init();
      showVideo();

      // adjust image positioning so it lines up with video
      $bigImage
      .css('position','relative')
      .imagesLoaded(adjustImagePositioning);
      // and on window resize
      $(window).on('resize', adjustImagePositioning);
    }

    function showVideo() {
      BV.show($('.screen').attr('data-video'),{ambient:true}); //ambient true means no sound
    }

  </script>

</div>